INSERT INTO regions (region_name) VALUES ('North Scotland'),
('South Scotland'),
('North West England'),
('North East England'),
('Yorkshire'),
('North Wales & Merseyside'),
('South Wales'),
('West Midlands'),
('East Midlands'),
('East England'),
('South West England'),
('South England'),
('London'),
('South East England'),
('England'),
('Scotland'),
('Wales');