name: Pylint
on: 
    workflow_dispatch: 
    push:
    pull_request: 

jobs:
    pylint:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v1
              with:
                python-version: '3.13'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pylint
            
            - name: Analyse Code
              run: |
                pylint **/*.py --rcfile ./.pylintrc --output-format=github