name: Pytest
on: 
    workflow_dispatch: 
    push:
    pull_request: 

jobs:
    pytest:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v1
              with:
                python-version: '3.13'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest

            - name: Combine and install all requirements
              run: |
                find . -name "requirements.txt" -exec sh -c 'cat "$1"; echo' _ {} \; > all-requirements.txt
                pip install -r all-requirements.txt

            - name: Analyse Code
              run: |
                pytest