name: Pytest
on: 
    workflow_dispatch: 
    push:
    pull_request: 

jobs:
    pytest:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                project: [energy-generation, dashboard, alerts, co2_extract, newsletter, power_outage_ETL]
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v1
              with:
                python-version: '3.13'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest

            - name: Install requirements for given folder
              run: |
                cd ${{ matrix.project }}
                pip install -r requirements.txt

            - name: Analyse Code
              run: |
                cd ${{ matrix.project }}
                pytest tests